# Generated by Django 5.0.6 on 2024-07-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
