# Generated by Django 5.0.1 on 2024-07-11 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0001_initial'),
        ('members', '0002_remove_memreg_formfile_alter_memreg_educ_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amenity_name', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=220, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('For Approval', 'For Apporval'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='For Approval', max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sched_from', models.DateField()),
                ('sched_to', models.DateField()),
                ('description', models.TextField()),
                ('maintenance_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Done', 'Done')], default='Upcoming', max_length=50)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('amenity', models.ForeignKey(db_column='amenity_id', on_delete=django.db.models.deletion.CASCADE, to='amenities.amenities')),
                ('contractor', models.ForeignKey(db_column='contractor_id', on_delete=django.db.models.deletion.CASCADE, to='contractors.contractors')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sched_from', models.DateTimeField()),
                ('sched_to', models.DateTimeField()),
                ('status', models.CharField(choices=[('For Approval', 'For Apporval'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='For Approval', max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('amenity', models.ForeignKey(db_column='amenity_id', on_delete=django.db.models.deletion.CASCADE, to='amenities.amenities')),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='members.memreg')),
            ],
        ),
    ]
