# Generated by Django 5.0.1 on 2024-07-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contractor_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('is_individual', models.BooleanField()),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('landline', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('address', models.TextField()),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
