# Generated by Django 5.0.6 on 2024-07-05 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemReg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_form_no', models.CharField(blank=True, max_length=50, null=True)),
                ('family_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=10, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('blk', models.IntegerField(blank=True, null=True)),
                ('lot', models.IntegerField(blank=True, null=True)),
                ('phase', models.IntegerField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('landline', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('fb_name', models.CharField(blank=True, max_length=50, null=True)),
                ('formFile', models.FileField(blank=True, null=True, upload_to='member_img/')),
                ('description', models.TextField(blank=True, null=True)),
                ('reg_status', models.CharField(choices=[('For Approval', 'FOR_APPROVAL'), ('Active', 'ACTIVE'), ('Suspension', 'SUSPENDED'), ('Disable', 'DISABLED')], default='FOR_APPROVAL', max_length=50)),
                ('educ', models.CharField(choices=[('Post_Grad', 'POSTGRAD'), ('College', 'COLLEGE'), ('High_School', 'HIGH_SCHOOL'), ('Elementary', 'ELEMENTARY')], max_length=50)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occupants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('givenname', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('relationship', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.memreg')),
            ],
        ),
    ]
