# Generated by Django 5.0.1 on 2024-07-13 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemReg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_form_no', models.CharField(blank=True, max_length=50, null=True)),
                ('family_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=10, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('blk', models.IntegerField(blank=True, null=True)),
                ('lot', models.IntegerField(blank=True, null=True)),
                ('phase', models.IntegerField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('landline', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('fb_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reg_status', models.CharField(choices=[('For Approval', 'For Approval'), ('Active', 'Active'), ('Suspension', 'Suspension'), ('Disable', 'Disable')], default='For Approval', max_length=50)),
                ('educ', models.CharField(choices=[('Post Graduate', 'Post Graduate'), ('College', 'College'), ('High School', 'High School'), ('Elementary', 'Elementary')], max_length=50)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occupants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('dob', models.CharField()),
                ('relationship', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='members.memreg')),
            ],
        ),
    ]
