# Generated by Django 5.0.1 on 2024-07-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memreg',
            name='formFile',
        ),
        migrations.AlterField(
            model_name='memreg',
            name='educ',
            field=models.CharField(choices=[('Post Graduate', 'Post Graduate'), ('College', 'College'), ('High School', 'High School'), ('Elementary', 'Elementary')], max_length=50),
        ),
        migrations.AlterField(
            model_name='memreg',
            name='reg_status',
            field=models.CharField(choices=[('For Approval', 'For Approval'), ('Active', 'Active'), ('Suspension', 'Suspension'), ('Disable', 'Disable')], default='For Approval', max_length=50),
        ),
        migrations.AlterField(
            model_name='occupants',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50),
        ),
    ]
